name: iplocation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:
      - codebuild-iplocation-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DB11LITEBIN.BIN.ZIP .
      - run: unzip DB11LITEBIN.BIN.ZIP -d .
      - run: rm DB11LITEBIN.BIN.ZIP
      - run: ls -la .
      - run: npm install -g aws-cdk
      - run: npm install -g aws-cdk-lib
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt --upgrade
      - run: cdk deploy IpLocationLookupUse1 --require-approval never