name: iplocation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:
      - codebuild-iplocation-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
      ### Download DB11LITEBIN from S3 with OIDC
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DB11LITEBIN.BIN.ZIP .
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DB11LITEBIN.updated lookup/DB11LITEBIN.updated
      - run: unzip -o DB11LITEBIN.BIN.ZIP -d .
      - run: mv IP2LOCATION-LITE-DB11.BIN lookup/IP2LOCATION-LITE-DB11.BIN
      ### Download DB11LITEBINIPV6 from S3 with OIDC
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DB11LITEBINIPV6.BIN.ZIP .
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DB11LITEBINIPV6.updated lookup/DB11LITEBINIPV6.updated
      - run: unzip -o DB11LITEBINIPV6.BIN.ZIP -d .
      - run: mv IP2LOCATION-LITE-DB11.IPV6.BIN lookup/IP2LOCATION-LITE-DB11.IPV6.BIN
      ### Download DBASNLITEBIN from S3 with OIDC
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DBASNLITEBIN.BIN.ZIP .
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DBASNLITEBIN.updated lookup/DBASNLITEBIN.updated
      - run: unzip -o DBASNLITEBIN.BIN.ZIP -d .
      - run: mv IP2LOCATION-LITE-ASN.BIN lookup/IP2LOCATION-LITE-ASN.BIN
      ### Download DBASNLITEBINIPV6 from S3 with OIDC
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DBASNLITEBINIPV6.BIN.ZIP .
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/DBASNLITEBINIPV6.updated lookup/DBASNLITEBINIPV6.updated
      - run: unzip -o DBASNLITEBINIPV6.BIN.ZIP -d .
      - run: mv IP2LOCATION-LITE-ASN.IPV6.BIN lookup/IP2LOCATION-LITE-ASN.IPV6.BIN
      ### Download PX12LITEBIN from S3 with OIDC
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/PX12LITEBIN.BIN.ZIP .
      - run: aws s3 cp s3://iplocation-staged-use1-lukach-io/PX12LITEBIN.updated lookup/PX12LITEBIN.updated
      - run: unzip -o PX12LITEBIN.BIN.ZIP -d .
      - run: mv IP2PROXY-LITE-PX12.BIN lookup/IP2PROXY-LITE-PX12.BIN
      ### Verify files exist
      - run: ls -lh .
      - run: ls -lh lookup/
      ### Deploy CDK Stack to Amazon Cloud
      - run: npm install -g aws-cdk
      - run: npm install -g aws-cdk-lib
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt --upgrade
      - run: cdk deploy IpLocationLookupUse1 --require-approval never